### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by SardineMilkshake** [D2R-Gimli/TinyMod#2]
I tried installing this but I cannot get it to work. The game just launches normally with the same graphics.

Does it only work for SP?

Any help would be greatly appreciated.

**Comment by D2R-Gimli** [comment]
It works for SP and Online.
Did you check out the README file? It should be all described in there. Maybe you missed to set the starting arguments in the battle.net launcher.
[](https://github.com/D2R-Gimli/TinyMod/blob/main/mods/tiny_README.txt)
